# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(637, 707)
        self.c_key = QtGui.QPushButton(Dialog)
        self.c_key.setGeometry(QtCore.QRect(10, 480, 71, 221))
        self.c_key.setText(_fromUtf8(""))
        self.c_key.setObjectName(_fromUtf8("c_key"))
        self.cs_key = QtGui.QPushButton(Dialog)
        self.cs_key.setGeometry(QtCore.QRect(50, 470, 51, 181))
        self.cs_key.setText(_fromUtf8(""))
        self.cs_key.setObjectName(_fromUtf8("cs_key"))
        self.d_key = QtGui.QPushButton(Dialog)
        self.d_key.setGeometry(QtCore.QRect(80, 480, 71, 221))
        self.d_key.setText(_fromUtf8(""))
        self.d_key.setObjectName(_fromUtf8("d_key"))
        self.ds_key = QtGui.QPushButton(Dialog)
        self.ds_key.setGeometry(QtCore.QRect(130, 470, 51, 181))
        self.ds_key.setText(_fromUtf8(""))
        self.ds_key.setObjectName(_fromUtf8("ds_key"))
        self.e_key = QtGui.QPushButton(Dialog)
        self.e_key.setGeometry(QtCore.QRect(150, 480, 71, 221))
        self.e_key.setText(_fromUtf8(""))
        self.e_key.setObjectName(_fromUtf8("e_key"))
        self.fs_key = QtGui.QPushButton(Dialog)
        self.fs_key.setGeometry(QtCore.QRect(270, 470, 51, 181))
        self.fs_key.setText(_fromUtf8(""))
        self.fs_key.setObjectName(_fromUtf8("fs_key"))
        self.f_key = QtGui.QPushButton(Dialog)
        self.f_key.setGeometry(QtCore.QRect(220, 480, 71, 221))
        self.f_key.setText(_fromUtf8(""))
        self.f_key.setObjectName(_fromUtf8("f_key"))
        self.a_key = QtGui.QPushButton(Dialog)
        self.a_key.setGeometry(QtCore.QRect(360, 480, 71, 221))
        self.a_key.setText(_fromUtf8(""))
        self.a_key.setObjectName(_fromUtf8("a_key"))
        self.g_key = QtGui.QPushButton(Dialog)
        self.g_key.setGeometry(QtCore.QRect(290, 480, 71, 221))
        self.g_key.setText(_fromUtf8(""))
        self.g_key.setObjectName(_fromUtf8("g_key"))
        self.gs_key = QtGui.QPushButton(Dialog)
        self.gs_key.setGeometry(QtCore.QRect(340, 470, 51, 181))
        self.gs_key.setText(_fromUtf8(""))
        self.gs_key.setObjectName(_fromUtf8("gs_key"))
        self.b_key = QtGui.QPushButton(Dialog)
        self.b_key.setGeometry(QtCore.QRect(430, 480, 71, 221))
        self.b_key.setText(_fromUtf8(""))
        self.b_key.setObjectName(_fromUtf8("b_key"))
        self.as_key = QtGui.QPushButton(Dialog)
        self.as_key.setGeometry(QtCore.QRect(410, 470, 51, 181))
        self.as_key.setText(_fromUtf8(""))
        self.as_key.setObjectName(_fromUtf8("as_key"))
        self.c2_key = QtGui.QPushButton(Dialog)
        self.c2_key.setGeometry(QtCore.QRect(500, 480, 71, 221))
        self.c2_key.setText(_fromUtf8(""))
        self.c2_key.setObjectName(_fromUtf8("c2_key"))
        self.master_gain_dial = QtGui.QDial(Dialog)
        self.master_gain_dial.setGeometry(QtCore.QRect(580, 0, 50, 64))
        self.master_gain_dial.setObjectName(_fromUtf8("master_gain_dial"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(580, 60, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 381, 91))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 58, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.dial = QtGui.QDial(self.frame)
        self.dial.setGeometry(QtCore.QRect(130, 0, 50, 64))
        self.dial.setObjectName(_fromUtf8("dial"))
        self.dial_2 = QtGui.QDial(self.frame)
        self.dial_2.setGeometry(QtCore.QRect(210, 0, 50, 64))
        self.dial_2.setObjectName(_fromUtf8("dial_2"))
        self.dial_3 = QtGui.QDial(self.frame)
        self.dial_3.setGeometry(QtCore.QRect(290, 0, 50, 64))
        self.dial_3.setObjectName(_fromUtf8("dial_3"))
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 81, 33))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(290, 60, 51, 19))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 381, 91))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 58, 19))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dial_4 = QtGui.QDial(self.frame_2)
        self.dial_4.setGeometry(QtCore.QRect(290, 0, 50, 64))
        self.dial_4.setObjectName(_fromUtf8("dial_4"))
        self.dial_5 = QtGui.QDial(self.frame_2)
        self.dial_5.setGeometry(QtCore.QRect(130, 0, 50, 64))
        self.dial_5.setObjectName(_fromUtf8("dial_5"))
        self.dial_6 = QtGui.QDial(self.frame_2)
        self.dial_6.setGeometry(QtCore.QRect(210, 0, 50, 64))
        self.dial_6.setObjectName(_fromUtf8("dial_6"))
        self.comboBox_2 = QtGui.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 40, 81, 33))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(290, 60, 51, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(10, 210, 381, 91))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 58, 19))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.dial_9 = QtGui.QDial(self.frame_3)
        self.dial_9.setGeometry(QtCore.QRect(210, 0, 50, 64))
        self.dial_9.setObjectName(_fromUtf8("dial_9"))
        self.dial_7 = QtGui.QDial(self.frame_3)
        self.dial_7.setGeometry(QtCore.QRect(290, 0, 50, 64))
        self.dial_7.setObjectName(_fromUtf8("dial_7"))
        self.dial_8 = QtGui.QDial(self.frame_3)
        self.dial_8.setGeometry(QtCore.QRect(130, 0, 50, 64))
        self.dial_8.setObjectName(_fromUtf8("dial_8"))
        self.comboBox_3 = QtGui.QComboBox(self.frame_3)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 40, 81, 33))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(290, 60, 51, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.e_key.raise_()
        self.d_key.raise_()
        self.c_key.raise_()
        self.cs_key.raise_()
        self.ds_key.raise_()
        self.f_key.raise_()
        self.a_key.raise_()
        self.g_key.raise_()
        self.gs_key.raise_()
        self.fs_key.raise_()
        self.b_key.raise_()
        self.as_key.raise_()
        self.c2_key.raise_()
        self.master_gain_dial.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", " Master", None))
        self.label_2.setText(_translate("Dialog", "Osc 1", None))
        self.comboBox.setItemText(0, _translate("Dialog", "Saw", None))
        self.comboBox.setItemText(1, _translate("Dialog", "Sin", None))
        self.comboBox.setItemText(2, _translate("Dialog", "Square", None))
        self.label_5.setText(_translate("Dialog", "Volume", None))
        self.label_3.setText(_translate("Dialog", "Osc 2", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Saw", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Sin", None))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Square", None))
        self.label_6.setText(_translate("Dialog", "Volume", None))
        self.label_4.setText(_translate("Dialog", "Osc 3", None))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Saw", None))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Sin", None))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Square", None))
        self.label_7.setText(_translate("Dialog", "Volume", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

